void nhapmatran(int a[][100], int &m, int &n);
bool ktmtdv(int a[][100], int m, int n);
int demx(int a[][100], int m, int n, int x);
int tongduong(int a[][100], int m, int n);
int tongam(int a[][100], int m, int n);
void nhapmatranr(float a[][100], int &m, int &n);
float tongduongr(float a[][100], int m, int n);
bool ktdongtang(float a[][100], int m, int n);
float maxmtr(float a[][100], int m, int n);
void vtmaxr(float a[][100], int m, int n);
bool dxduongcheochinh(float a[][100], int m, int n);
bool ktnt(float x);
void nguyentomax(float a[][100], int m, int n);
void outb3(int a[][100], int m, int n);
int maxdong(int a[][100], int m, int n, int dong);
int mincot(int a[][100], int m, int n, int cot);
void mangB(int a[][100], int m, int n);
int tongdong(int a[][100], int m, int n, int dong);
void outb4(int a[][100], int m, int n);
float tongtamgiactren(float a[][100], int m, int n);