void menu(int &choice);
void ct1();
void ct2();
void ct3();
void ct4();
void ct5();
void nhap(int &d, int &m, int &y);
bool ktnamnhuan(int y);
void xuatngaysau(int d, int m, int y);
void xuatngaytruoc(int d, int m, int y);
void trangay(int d, int m, int y);
bool kthople(int d, int m, int y);
int songay(int m, int y);
float spand(int d1, int m1, int y1, int d2, int m2, int y2);
float spanm(int d1, int m1, int y1, int d2, int m2, int y2);
float spany(int d1, int m1, int y1, int d2, int m2, int y2);
